### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hendrash**
I created a csv to sql  converter in python its called csvToSql.py

### CODE REVIEW

**Comment by MarcusWichelmann** [comment]
Thank you for your contribution. Could you add more documentation and comments please? I don't get, what this code does. :smile: 

Ah, and it will not be enough to just insert the CSV data 1:1 into the SQL database. The SQL database consists of many tables and the structure is different from the excel sheets. There also needs to be some kind of mapping in place to convert fields from the excel sheets to structured values as defined in our structure (see below). The importing tool requires a little bit more intelligence to do it's task.

You could either try to reproduce the schema by generating SQL insert strings that fit into this schema, or (which might be a lot easier and safer to do) do it in C# and just call the existing database logic that already does the whole database communication for you and has the database schema already implemented in an object oriented manner.

If you'd like to do it in C#, please let me know in advance so I can prepare a simple importing project for you where you can add the code. Of course it's hard to learn a knew language, but I'll support you. And the basic operations are not **that** different from how you know them from the Java world.

But when you want to reimplement the database logic in Python, then this should probably be it's own repository. I don't want to mix this into the backend code because it requires a completely different testing and building approach (because it's another language) and would break the automatic pull request testing procedure.

That's our current SQL structure as discussed in one of our meetings: structure
Keep in mind that it might be subject to (minor) changes.

**Comment by hendrash** [comment]
Marcus is this where I should be messaging to ?

**Comment by MarcusWichelmann** [comment]
@hendrash Yes, this is the place for everything that's realted to your pull request (this thing here).

**Comment by hendrash** [comment]
run :
Make sure you have mysql installed and configured
> sudo apt-get update
> sudo apt-get install xlsx2csv
> sudo apt-get install mysql-python-connector
> xlsx2csv Kontrolldaten-2012.xlsx > Kontrolldaten
> vim csvToSql.py
go to line 152 and pick what method you want to run by default there is a insert a create table method that will run. 
> python csvToSql.py

**Comment by hendrash** [comment]
Selection_008

**Comment by MarcusWichelmann** [comment]
@hendrash Yeah I've seen this. Doesn't change anything about the fact, that your code doesn't respect our database schema. Please compare the diagram I posted above with your screenshot and you'll see what I'm talking about. :smile:

**Pull request closed without merging**
